### ISSUE TITLE
Data Package URL

### ISSUE THREAD

**Issue by WendellGong** [ethz-asl/active_learning_for_segmentation#4]
Hi!
   I try to download the Data Package you mentioned in README, but it seems to have the same URL with the Flat Environment which does NOT include the replayset, testsets and pth. Is the data package URL wrong?
   Thanks!

**Comment by renezurbruegg** [comment]
Hi

Sorry for that. I updated the link. It should work now!

**Comment by WendellGong** [comment]
> Hi
> 
> Sorry for that. I updated the link. It should work now!

Ok，I've got that, thanks for your updating!
